package main

import (
	"github.com/amazon-route-53-resolver/mcp-server/config"
	"github.com/amazon-route-53-resolver/mcp-server/models"
	tools_x_amz_target_route53resolver_tagresource "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_tagresource"
	tools_x_amz_target_route53resolver_createoutpostresolver "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_createoutpostresolver"
	tools_x_amz_target_route53resolver_createfirewalldomainlist "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_createfirewalldomainlist"
	tools_x_amz_target_route53resolver_getoutpostresolver "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getoutpostresolver"
	tools_x_amz_target_route53resolver_listfirewalldomainlists "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listfirewalldomainlists"
	tools_x_amz_target_route53resolver_getresolverquerylogconfigpolicy "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverquerylogconfigpolicy"
	tools_x_amz_target_route53resolver_deleteoutpostresolver "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_deleteoutpostresolver"
	tools_x_amz_target_route53resolver_putresolverquerylogconfigpolicy "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_putresolverquerylogconfigpolicy"
	tools_x_amz_target_route53resolver_associateresolverquerylogconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_associateresolverquerylogconfig"
	tools_x_amz_target_route53resolver_listresolverendpoints "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverendpoints"
	tools_x_amz_target_route53resolver_updateresolverrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updateresolverrule"
	tools_x_amz_target_route53resolver_getresolverendpoint "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverendpoint"
	tools_x_amz_target_route53resolver_listfirewalldomains "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listfirewalldomains"
	tools_x_amz_target_route53resolver_listresolverconfigs "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverconfigs"
	tools_x_amz_target_route53resolver_getresolverquerylogconfigassociation "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverquerylogconfigassociation"
	tools_x_amz_target_route53resolver_getfirewalldomainlist "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getfirewalldomainlist"
	tools_x_amz_target_route53resolver_updateoutpostresolver "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updateoutpostresolver"
	tools_x_amz_target_route53resolver_deleteresolverquerylogconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_deleteresolverquerylogconfig"
	tools_x_amz_target_route53resolver_getfirewallrulegrouppolicy "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getfirewallrulegrouppolicy"
	tools_x_amz_target_route53resolver_associateresolverendpointipaddress "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_associateresolverendpointipaddress"
	tools_x_amz_target_route53resolver_listresolverendpointipaddresses "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverendpointipaddresses"
	tools_x_amz_target_route53resolver_updateresolverendpoint "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updateresolverendpoint"
	tools_x_amz_target_route53resolver_createfirewallrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_createfirewallrule"
	tools_x_amz_target_route53resolver_deleteresolverrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_deleteresolverrule"
	tools_x_amz_target_route53resolver_deletefirewalldomainlist "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_deletefirewalldomainlist"
	tools_x_amz_target_route53resolver_disassociateresolverrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_disassociateresolverrule"
	tools_x_amz_target_route53resolver_getresolverquerylogconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverquerylogconfig"
	tools_x_amz_target_route53resolver_updatefirewallrulegroupassociation "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updatefirewallrulegroupassociation"
	tools_x_amz_target_route53resolver_listtagsforresource "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listtagsforresource"
	tools_x_amz_target_route53resolver_importfirewalldomains "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_importfirewalldomains"
	tools_x_amz_target_route53resolver_listresolverquerylogconfigassociations "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverquerylogconfigassociations"
	tools_x_amz_target_route53resolver_listfirewallrulegroupassociations "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listfirewallrulegroupassociations"
	tools_x_amz_target_route53resolver_updateresolverdnssecconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updateresolverdnssecconfig"
	tools_x_amz_target_route53resolver_associateresolverrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_associateresolverrule"
	tools_x_amz_target_route53resolver_listfirewallrulegroups "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listfirewallrulegroups"
	tools_x_amz_target_route53resolver_listresolverrules "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverrules"
	tools_x_amz_target_route53resolver_getresolverdnssecconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverdnssecconfig"
	tools_x_amz_target_route53resolver_getfirewallrulegroupassociation "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getfirewallrulegroupassociation"
	tools_x_amz_target_route53resolver_putresolverrulepolicy "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_putresolverrulepolicy"
	tools_x_amz_target_route53resolver_deletefirewallrulegroup "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_deletefirewallrulegroup"
	tools_x_amz_target_route53resolver_associatefirewallrulegroup "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_associatefirewallrulegroup"
	tools_x_amz_target_route53resolver_getfirewallconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getfirewallconfig"
	tools_x_amz_target_route53resolver_getresolverconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverconfig"
	tools_x_amz_target_route53resolver_disassociateresolverquerylogconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_disassociateresolverquerylogconfig"
	tools_x_amz_target_route53resolver_createresolverendpoint "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_createresolverendpoint"
	tools_x_amz_target_route53resolver_getresolverrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverrule"
	tools_x_amz_target_route53resolver_updatefirewallconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updatefirewallconfig"
	tools_x_amz_target_route53resolver_deletefirewallrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_deletefirewallrule"
	tools_x_amz_target_route53resolver_disassociateresolverendpointipaddress "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_disassociateresolverendpointipaddress"
	tools_x_amz_target_route53resolver_getresolverrulepolicy "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverrulepolicy"
	tools_x_amz_target_route53resolver_listresolverruleassociations "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverruleassociations"
	tools_x_amz_target_route53resolver_updatefirewalldomains "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updatefirewalldomains"
	tools_x_amz_target_route53resolver_untagresource "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_untagresource"
	tools_x_amz_target_route53resolver_createresolverquerylogconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_createresolverquerylogconfig"
	tools_x_amz_target_route53resolver_disassociatefirewallrulegroup "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_disassociatefirewallrulegroup"
	tools_x_amz_target_route53resolver_listfirewallconfigs "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listfirewallconfigs"
	tools_x_amz_target_route53resolver_updateresolverconfig "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updateresolverconfig"
	tools_x_amz_target_route53resolver_getresolverruleassociation "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getresolverruleassociation"
	tools_x_amz_target_route53resolver_putfirewallrulegrouppolicy "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_putfirewallrulegrouppolicy"
	tools_x_amz_target_route53resolver_createfirewallrulegroup "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_createfirewallrulegroup"
	tools_x_amz_target_route53resolver_updatefirewallrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_updatefirewallrule"
	tools_x_amz_target_route53resolver_createresolverrule "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_createresolverrule"
	tools_x_amz_target_route53resolver_listfirewallrules "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listfirewallrules"
	tools_x_amz_target_route53resolver_listresolverdnssecconfigs "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverdnssecconfigs"
	tools_x_amz_target_route53resolver_listresolverquerylogconfigs "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listresolverquerylogconfigs"
	tools_x_amz_target_route53resolver_deleteresolverendpoint "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_deleteresolverendpoint"
	tools_x_amz_target_route53resolver_getfirewallrulegroup "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_getfirewallrulegroup"
	tools_x_amz_target_route53resolver_listoutpostresolvers "github.com/amazon-route-53-resolver/mcp-server/tools/x_amz_target_route53resolver_listoutpostresolvers"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_route53resolver_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_route53resolver_createoutpostresolver.CreateCreateoutpostresolverTool(cfg),
		tools_x_amz_target_route53resolver_createfirewalldomainlist.CreateCreatefirewalldomainlistTool(cfg),
		tools_x_amz_target_route53resolver_getoutpostresolver.CreateGetoutpostresolverTool(cfg),
		tools_x_amz_target_route53resolver_listfirewalldomainlists.CreateListfirewalldomainlistsTool(cfg),
		tools_x_amz_target_route53resolver_getresolverquerylogconfigpolicy.CreateGetresolverquerylogconfigpolicyTool(cfg),
		tools_x_amz_target_route53resolver_deleteoutpostresolver.CreateDeleteoutpostresolverTool(cfg),
		tools_x_amz_target_route53resolver_putresolverquerylogconfigpolicy.CreatePutresolverquerylogconfigpolicyTool(cfg),
		tools_x_amz_target_route53resolver_associateresolverquerylogconfig.CreateAssociateresolverquerylogconfigTool(cfg),
		tools_x_amz_target_route53resolver_listresolverendpoints.CreateListresolverendpointsTool(cfg),
		tools_x_amz_target_route53resolver_updateresolverrule.CreateUpdateresolverruleTool(cfg),
		tools_x_amz_target_route53resolver_getresolverendpoint.CreateGetresolverendpointTool(cfg),
		tools_x_amz_target_route53resolver_listfirewalldomains.CreateListfirewalldomainsTool(cfg),
		tools_x_amz_target_route53resolver_listresolverconfigs.CreateListresolverconfigsTool(cfg),
		tools_x_amz_target_route53resolver_getresolverquerylogconfigassociation.CreateGetresolverquerylogconfigassociationTool(cfg),
		tools_x_amz_target_route53resolver_getfirewalldomainlist.CreateGetfirewalldomainlistTool(cfg),
		tools_x_amz_target_route53resolver_updateoutpostresolver.CreateUpdateoutpostresolverTool(cfg),
		tools_x_amz_target_route53resolver_deleteresolverquerylogconfig.CreateDeleteresolverquerylogconfigTool(cfg),
		tools_x_amz_target_route53resolver_getfirewallrulegrouppolicy.CreateGetfirewallrulegrouppolicyTool(cfg),
		tools_x_amz_target_route53resolver_associateresolverendpointipaddress.CreateAssociateresolverendpointipaddressTool(cfg),
		tools_x_amz_target_route53resolver_listresolverendpointipaddresses.CreateListresolverendpointipaddressesTool(cfg),
		tools_x_amz_target_route53resolver_updateresolverendpoint.CreateUpdateresolverendpointTool(cfg),
		tools_x_amz_target_route53resolver_createfirewallrule.CreateCreatefirewallruleTool(cfg),
		tools_x_amz_target_route53resolver_deleteresolverrule.CreateDeleteresolverruleTool(cfg),
		tools_x_amz_target_route53resolver_deletefirewalldomainlist.CreateDeletefirewalldomainlistTool(cfg),
		tools_x_amz_target_route53resolver_disassociateresolverrule.CreateDisassociateresolverruleTool(cfg),
		tools_x_amz_target_route53resolver_getresolverquerylogconfig.CreateGetresolverquerylogconfigTool(cfg),
		tools_x_amz_target_route53resolver_updatefirewallrulegroupassociation.CreateUpdatefirewallrulegroupassociationTool(cfg),
		tools_x_amz_target_route53resolver_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_route53resolver_importfirewalldomains.CreateImportfirewalldomainsTool(cfg),
		tools_x_amz_target_route53resolver_listresolverquerylogconfigassociations.CreateListresolverquerylogconfigassociationsTool(cfg),
		tools_x_amz_target_route53resolver_listfirewallrulegroupassociations.CreateListfirewallrulegroupassociationsTool(cfg),
		tools_x_amz_target_route53resolver_updateresolverdnssecconfig.CreateUpdateresolverdnssecconfigTool(cfg),
		tools_x_amz_target_route53resolver_associateresolverrule.CreateAssociateresolverruleTool(cfg),
		tools_x_amz_target_route53resolver_listfirewallrulegroups.CreateListfirewallrulegroupsTool(cfg),
		tools_x_amz_target_route53resolver_listresolverrules.CreateListresolverrulesTool(cfg),
		tools_x_amz_target_route53resolver_getresolverdnssecconfig.CreateGetresolverdnssecconfigTool(cfg),
		tools_x_amz_target_route53resolver_getfirewallrulegroupassociation.CreateGetfirewallrulegroupassociationTool(cfg),
		tools_x_amz_target_route53resolver_putresolverrulepolicy.CreatePutresolverrulepolicyTool(cfg),
		tools_x_amz_target_route53resolver_deletefirewallrulegroup.CreateDeletefirewallrulegroupTool(cfg),
		tools_x_amz_target_route53resolver_associatefirewallrulegroup.CreateAssociatefirewallrulegroupTool(cfg),
		tools_x_amz_target_route53resolver_getfirewallconfig.CreateGetfirewallconfigTool(cfg),
		tools_x_amz_target_route53resolver_getresolverconfig.CreateGetresolverconfigTool(cfg),
		tools_x_amz_target_route53resolver_disassociateresolverquerylogconfig.CreateDisassociateresolverquerylogconfigTool(cfg),
		tools_x_amz_target_route53resolver_createresolverendpoint.CreateCreateresolverendpointTool(cfg),
		tools_x_amz_target_route53resolver_getresolverrule.CreateGetresolverruleTool(cfg),
		tools_x_amz_target_route53resolver_updatefirewallconfig.CreateUpdatefirewallconfigTool(cfg),
		tools_x_amz_target_route53resolver_deletefirewallrule.CreateDeletefirewallruleTool(cfg),
		tools_x_amz_target_route53resolver_disassociateresolverendpointipaddress.CreateDisassociateresolverendpointipaddressTool(cfg),
		tools_x_amz_target_route53resolver_getresolverrulepolicy.CreateGetresolverrulepolicyTool(cfg),
		tools_x_amz_target_route53resolver_listresolverruleassociations.CreateListresolverruleassociationsTool(cfg),
		tools_x_amz_target_route53resolver_updatefirewalldomains.CreateUpdatefirewalldomainsTool(cfg),
		tools_x_amz_target_route53resolver_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_route53resolver_createresolverquerylogconfig.CreateCreateresolverquerylogconfigTool(cfg),
		tools_x_amz_target_route53resolver_disassociatefirewallrulegroup.CreateDisassociatefirewallrulegroupTool(cfg),
		tools_x_amz_target_route53resolver_listfirewallconfigs.CreateListfirewallconfigsTool(cfg),
		tools_x_amz_target_route53resolver_updateresolverconfig.CreateUpdateresolverconfigTool(cfg),
		tools_x_amz_target_route53resolver_getresolverruleassociation.CreateGetresolverruleassociationTool(cfg),
		tools_x_amz_target_route53resolver_putfirewallrulegrouppolicy.CreatePutfirewallrulegrouppolicyTool(cfg),
		tools_x_amz_target_route53resolver_createfirewallrulegroup.CreateCreatefirewallrulegroupTool(cfg),
		tools_x_amz_target_route53resolver_updatefirewallrule.CreateUpdatefirewallruleTool(cfg),
		tools_x_amz_target_route53resolver_createresolverrule.CreateCreateresolverruleTool(cfg),
		tools_x_amz_target_route53resolver_listfirewallrules.CreateListfirewallrulesTool(cfg),
		tools_x_amz_target_route53resolver_listresolverdnssecconfigs.CreateListresolverdnssecconfigsTool(cfg),
		tools_x_amz_target_route53resolver_listresolverquerylogconfigs.CreateListresolverquerylogconfigsTool(cfg),
		tools_x_amz_target_route53resolver_deleteresolverendpoint.CreateDeleteresolverendpointTool(cfg),
		tools_x_amz_target_route53resolver_getfirewallrulegroup.CreateGetfirewallrulegroupTool(cfg),
		tools_x_amz_target_route53resolver_listoutpostresolvers.CreateListoutpostresolversTool(cfg),
	}
}
